# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    flutter_style_todos: false # https://dart-lang.github.io/linter/lints/flutter_style_todos.html