name: limited_characters_diary
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+33
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  app_tracking_transparency: ^2.0.4
  awesome_dialog: ^3.0.2
  cloud_firestore: ^4.13.3
  collection: ^1.17.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.1.1
  device_preview: ^1.1.0
  firebase_analytics: ^10.2.0
  firebase_app_check: ^0.2.1+6
  firebase_auth: ^4.4.0
  firebase_crashlytics: ^3.4.9
  firebase_core: ^2.9.0
  firebase_messaging: ^14.5.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_launcher_icons: ^0.13.0
  flutter_local_notifications: ^16.3.0
  flutter_phoenix: ^1.1.1
  flutter_screen_lock: ^9.0.1
  flutter_slidable: ^3.0.0
  flutter_timezone: ^1.0.8
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  google_mobile_ads: ^2.4.0
  google_sign_in: ^6.1.6
  hooks_riverpod: ^2.3.0
  in_app_review: ^2.0.6
  intl: ^0.18.1
  json_annotation: ^4.8.0
  package_info_plus: ^3.0.3
  settings_ui: ^2.0.2
  shared_preferences: ^2.1.0
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^5.0.0
  sizer: ^2.0.15
  timezone: ^0.9.1
  url_launcher: ^6.1.10
  uuid: ^3.0.7
  version: ^3.0.2
  webview_flutter: ^4.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  isar_generator: ^3.0.5
  json_serializable: ^6.6.1
  pedantic_mono: any

flutter_native_splash:
  color: '#6AB5E6'
  image: 'assets/images/splash.png'
#  color_dark: '#262626'
#  image_dark: 'assets/images/splash.png'
  fullscreen: false
  android_12:
    icon_background_color: '#6AB5E6'
    image: 'assets/images/splash_android12.png'
#    icon_background_color_dark: '#262626'
#    image_dark: 'assets/images/splash_android12.png'

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icon.png'
  adaptive_icon_background: '#6AB5E6'
  adaptive_icon_foreground: 'assets/images/icon_adaptive_foreground.png'

flutter:
  fonts:
    - family: M_PLUS_Rounded_1c
      fonts:
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Light.ttf
          weight: 300
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Regular.ttf
          weight: 400
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Black.ttf
          weight: 900
  uses-material-design: true

  assets:
   - assets/images/
